### ISSUE TITLE
module is undefined

### ISSUE THREAD

**Issue by Pisamad** [gcochard/p4-oo#3]
When I trye the following code : 

``` javascript
var P4 = require("p4-oo");
var p4 = new P4();

p4.setOpts({env:{P4CHARSET:'utf8',P4IGNORE:'P4.ignore'}});
p4.setOpts({env:{P4PORT:'p4-corp:1666',P4USER:'dupont'}});

p4.runCommand("clients", function(err, stdout) {
    if(err) console.error(err.message);
    console.log(stdout);
});
```

I've a windows popup : 

> Script : C:.....\node_modules\p4-oo\lib\p4.js
> Line : 15
> Char : 1
> Error : 'module' is undefined
> Code : 800A1391
> Source Micosoft JScript runtime error

**Comment by gcochard** [comment]
This module is written to be run with node.js, it looks like you're trying to execute it with the Microsoft JScript runtime, which does not expose the CommonJS `module` API.

**Comment by Pisamad** [comment]
In fact, I use Node.js in Win7 ...

_Pierre DUOT - 06 46 91 74 34 - 60, rue de Chateaugiron, RennesAdoptez
l'éco-attitude http://www.ecoattitude.org. N'imprimez ce mail que si
c'est vraiment nécessaire_

2015-04-01 19:05 GMT+02:00 Greg Cochard notifications@github.com:

**Comment by gcochard** [comment]
If you are getting this error `Source Micosoft JScript runtime error` then it means it is running in the Microsoft JScript runtime, not Node.js. The fact that you get a windows popup additionally suggests that is the case. Node.js will not pop up a modal dialog to give you a syntax error. It will show it on the cli.

Additionally, since it uses `child_process.exec` to run p4, you must have the p4 binary in your PATH.

What _could_ be happening is that when p4.js execs p4, it finds p4.js (the file node is running) in the pwd (because windows puts the pwd in the PATH) and runs _that_. Windows will pick the interpreter it _thinks_ should open javascript and that's the Microsoft JScript runtime.

This module has not been tested on windows, nor do I intend to implement windows compatibility, as I do not need it for my use-case. I'd be happy to accept a pull request with the changes necessary to support windows.

PS: If you have p4v, there is a [javascript api](http://www.perforce.com/perforce/doc.current/manuals/p4jsapi/) embedded in it that you can use as opposed to this module. It will be faster.

**Comment by Pisamad** [comment]
cool. I understand your explanation. I could do some tests tomorrow and I
will take you informed.
thank you

**Comment by Pisamad** [comment]
I've checked my config I've understund the issue.
1. p4.cwd is set to __dirname which is the relative to the local module. That means that p4.cwd point to ...\p4-oo\lib and it's not what we want.
2. with p4.runCommand(), the system environment is not passed to the exec function. So PATH is lost and exec doesn't find where p4 exe is.
So, if I change cwd and if I pass the PATH var in env, It's working ! :-)

**Comment by gcochard** [comment]
Awesome! Glad it works on windows without (too much) extra work! Do you think it'd be better to start off with the p4.cwd set to the `process.pwd`?

**Comment by Pisamad** [comment]
Yes,  I think it'd be better to do that. Maybe it could be good to setup the options.env at least with the PATH.

**Comment by gcochard** [comment]
I'll have this fixed shortly.
